sudo: required
services:
  - docker
before_install:
  - docker build -t akolk/datascience-notebook .
script:
  - docker images akolk/datascience-notebook
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS";
    docker push cinhtau/elasticsearch;
    fi
