sudo: required
services:
  - docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=akolk/datascience-notebook
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64 
before_install:
  - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  - docker build -t $REPO .
deploy:
  provider: script
  script: bash ./docker_push
  on:
    branch: master
script:
  - docker images $REPO
